### ISSUE TITLE
Installation problem on Ubuntu-MATE

### ISSUE THREAD

**Issue by torabi12** [medpaf/medsec#3]
Hello,

I wanted to install hawk on my new Ubuntu-MATE 22.04.1, which is running in VMWare Workstation Pro 16 and I got some error messages like:

![kép](https://user-images.githubusercontent.com/98665813/192038995-340789d8-6239-49ec-820a-a165c947286c.png)

![kép](https://user-images.githubusercontent.com/98665813/192039084-27b2de6d-39ab-42a0-9164-ef8cc1cff50b.png)

![kép](https://user-images.githubusercontent.com/98665813/192039170-85abe4b1-69a9-45c0-82c4-44bdbc987a0d.png)

Could you help how to fix the installation?
I have chosen the 1st option at the beginning of the process as I have Ubuntu.

Regards,
Torabi

**Comment by joao-vitor-souza** [comment]
@torabi12, I had the same problem and it looks like `pip` cannot resolve the version of the dependencies, I tested some versions but no success. @medpaf could you provide the package versions you used?

**Comment by medpaf** [comment]
@joao-vitor-souza @torabi12 I run into this isse myself but have you tried to use the tool? Please ignore the error messages and try the tool. In my case everything works fine. If you run into problems let me know. Regards
